# Generated by Django 4.2.3 on 2023-07-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnairea',
            old_name='accounts',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questionnaireb',
            old_name='accounts',
            new_name='user',
        ),
    ]
