# Generated by Django 4.2.3 on 2023-07-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentportfolio',
            old_name='accounts',
            new_name='user',
        ),
    ]
